services:
  vaultwarden:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${VAULTWARDEN_IMAGE}:${VAULTWARDEN_TAG}
    restart: unless-stopped
    volumes:
      - vw-data:/data/
    environment:
      DOMAIN: ${SITE_URL},www.${SITE_URL}
      WEBSOCKET_ENABLED: true
      SIGNUPS_ALLOWED: true
      VIRTUAL_HOST: ${SITE_URL},www.${SITE_URL}
      LETSENCRYPT_HOST: ${SITE_URL},www.${SITE_URL}

volumes:
  vw-data:

networks:
  default:
    name: ${NETWORK}
    external: true
